#include "parser.h"

static TokenType OPERATOR_TOKENTYPES[] = {
  INC, DEC, LEFT_PAREN, RIGHT_PAREN, LEFT_BRACKET, RIGHT_BRACKET,
  PERIOD, ADD, SUBTRACT, NOT, BIT_NOT,

  EXPONENT, MULTIPLY, DIVIDE, MOD, BIT_LEFT, BIT_RIGHT,

  GREATER, LESS, GREATER_EQ, LESS_EQ, EQ_EQ, NOT_EQ,

  BIT_AND, BIT_XOR, BIT_OR, AND, XOR, OR,

  EQ, ADD_EQ, SUBTRACT_EQ, EXPONENT_EQ, MULTIPLY_EQ, DIVIDE_EQ, 
  MOD_EQ, AND_EQ, XOR_EQ, OR_EQ, BIT_LEFT_EQ, BIT_RIGHT_EQ
};


static ParseOperatorType PARSE_OPERATOR_ENUMS[] = {
  INC_OP, DEC_OP, LEFT_PAREN_OP, RIGHT_PAREN_OP, LEFT_BRACKET_OP, RIGHT_BRACKET_OP,
  PERIOD, ADD_OP, SUBTRACT_OP, NOT_OP, BIT_NOT_OP,

  EXPONENT, MULTIPLY_OP, DIVIDE_OP, MOD_OP, BIT_LEFT_OP, BIT_RIGHT_OP,

  GREATER, LESS_OP, GREATER_EQ_OP, LESS_EQ_OP, EQ_EQ_OP, NOT_EQ_OP,

  BIT_AND, BIT_XOR_OP, BIT_OR_OP, AND_OP, XOR_OP, OR_OP,

  EQ, ADD_EQ_OP, SUBTRACT_EQ_OP, EXPONENT_EQ_OP, MULTIPLY_EQ_OP, DIVIDE_EQ_OP, 
  MOD_EQ, AND_EQ_OP, XOR_EQ_OP, OR_EQ_OP, BIT_LEFT_EQ_OP, BIT_RIGHT_EQ_OP
};





